import Head from "next/head";
import styled from "styled-components";

const LayoutWrapper = styled.div`
  position: relative;

  .side-nav {
    /* padding: 1rem 0; */
    font-family: inherit;
    font-size: 1.6rem;

    /* .menu-btn {
      display: none;
    } */
   
    .side-nav-item {
      height: 6rem;
      display: flex;
      align-items: center;
      padding-left: 2rem;
      cursor: pointer;
    }

    
    .help-icon{
      display: none;
    }
  }
  svg {
    margin-right: 1.5rem;
  }

  #hsbar{
    margin-bottom: 1rem;
  }

  @media screen and (max-width: 768px) {
    .side-nav{
        width: 12%;
        .help-icon{
      display: block;
    }
    }
    .help-text{
      display: none;
}

    /* .side-nav .menu-btn {
      display: block;
      padding-left: 2rem;
      font-size: 4rem;
    } */
    .side-nav-item a{
      display: none;
    }
    .main-content{
      width: 88%;
    }
  }
  @media screen and (max-width: 414px) {
    .side-nav {
      display: none;
    }
    .main-content{
      width: 100%;
      padding: 3rem 1.5rem;
      .asset-figures{
        flex-direction: column;
        align-items: flex-start;
        margin-top: 1.8rem;
      }
    }
  }
`;
const DashBoardContainer = ({ children }) => (
  <>
    <Head>
    <title>Asset Tracker | Meristem Trustees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <LayoutWrapper className="font-Poppins">{children}</LayoutWrapper>
  </>
  
);
export default DashBoardContainer;
