import Head from "next/head";
import styled from "styled-components";

const LayoutWrapper = styled.div`
  position: relative;

  .side-nav {
    /* padding: 1rem 0; */
    font-family: inherit;
    font-size: 1.6rem;
    .side-nav-item {
      height: 6rem;
      display: flex;
      align-items: center;
      padding-left: 2rem;
      cursor: pointer;
    }
  }
  svg {
    margin-right: 1.5rem;
  }

  #hsbar{
    margin-bottom: 1rem;
  }

  @media screen and (max-width: 768px) {
    .side-nav-item a{
      display: none;
    }
  }
  @media screen and (max-width: 414px) {
    .main-content{
      /* width: 100%; */
      .asset-figures{
        align-items: flex-start;
      }
    }
  }
`;
const DashBoardContainer = ({ children }) => (
  <>
    <Head>
    <title>Asset Tracker | Meristem Trustees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <LayoutWrapper className="font-Poppins">{children}</LayoutWrapper>
  </>
  
);
export default DashBoardContainer;
