const Signup = () => {

    const handleSubmit = (e) => {
      e.preventDefault();
      setshowSubmission(false)
    };
  
    const [progressTrack, setProgressTrack] = useState(0);
    const [showFirstName, setshowFirstName] = useState("");
    const [showLasttName, setshowLasttName] = useState("");
    const [showEmail, setshowEmail] = useState("");
    const [showPhoneNumber, setshowPhoneNumber] = useState("");
    const [showConfirmEmail, setshowConfirmEmail] = useState("");
    const [showPassword, setshowPassword] = useState("");
    const [showConfirmPassword, setshowConfirmPassword] = useState("");
    const [showSubmission, setshowSubmission] = useState("true");
  
    return (
      <div>
        <Head>
          <title>Asset Tracker | Meristem Trustees</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex">
          {/* The lefttHand side*/}
          <div className="bg-[#BBF1D1] w-1/2 h-[43.4rem] hidden md:block md:w-50% lg:w-1/2 lg:block ">
            <div className="container ml-[4rem] mt-7 mb-[6rem] w-[10rem] h-[2rem] sm:hidden md:block lg:block">
              <Image src={logo} alt="MeristemLogo" /> {/* Meristem logo */}
            </div>
  
            <div className=" md:block md:w-[20rem] md:ml-[2rem] lg:block lg:w-[28rem] lg:ml-[4rem] ">
              <div className="mb-3 md:w-[10rem] lg:[25rem]">
                <h1 className="container font-Poppins text-[#345C45] md:w-[20rem] md:text-2xl lg:text-5xl lg:w-[28rem]  border ">
                  Keep track of all your assets on a single dashboard
                </h1>
              </div>
  
              <div className="container hidden md:block md:w-[20rem] lg:block lg:w-[27rem] border">
                <p className="font-Poppins text-[#345C45] md:w-[20rem] border">
                  Sign up now to easily keep track of your assets, designated
                  beneficiaries and receive estate planning products tailored to
                  your assets.
                </p>
              </div>
            </div>
  
            {/* Section for the block images beneath It conatins 3 block images */}
            {/* <div className="flex-wrap justify-between h-[15.4rem] border">
                <Image className="min-w-0 min-h-0 border" src={Bigblock} alt="Bigblock" important/>
                <Image className="min-w-0 min-h-0" src={Biggerblock} alt="Biggerblock" important />
                <Image className="min-w-[0] min-h-[0]" src={Biggstblock} alt="Biggstblock" important/>
              </div> */}
          </div>
          {/*End of LefttHand side*/}
  
          {/* The RightHand side*/}
          <div className="container mx-auto mb-[6rem] w-[10rem] h-[2rem] border md:hidden lg:hidden">
              <Image src={logo} alt="MeristemLogo" /> {/* Meristem logo */}
          </div>
  
          <div className="bg-white w-300 h-[28rem] sm:mx-auto md:mx-auto md:block md:w-1/2 md:h-[43.4rem] lg:mx-auto lg:w-1/2 lg:h-[43.4rem] border ">
            <div className=" container mx-auto w-[24rem] h-[30rem] mt-[4rem]  ">
              <h2 className="font-Poppins text-2xl md:text-3xl lg:text-4xl text-[#345C45] mb-2">
                Sign Up
              </h2>
              <div className="flex mb-10">
                <h4 className="font-Poppins">Already have an account?</h4>
                <span className="ml-3 text-[#345C45] font-Poppins">
                  <b>
                    <Link href="#">Log in</Link>
                  </b>
                </span>{" "}
              </div>
  
              {progressTrack === 0 ? (
  
                /* Form- Section 1 */
                <form
                  id="SignUp" 
                  className=" mb-5">
                  <div className="container">
                    <label className="font-Poppins ">First Name</label>
                    <br />
                    <input
                      onChange={(e) => setshowFirstName(e.target.value)}
                      type="text"
                      id="fname"
                      name="fname"
                      className="w-[371px] font-Poppins h-[38px] p-2 mb-5 bg-[#F3F3F3] rounded-md"
                      placeholder="First-name"
                      required
                    />
                  </div>
  
                  <div className="container">
                    <label className="font-Poppins">Last Name</label>
                    <br />
                    <input
                      onChange={(e) => setshowLasttName(e.target.value)}
                      type="text"
                      id="lname"
                      name="lname"
                      className="w-[371px] font-Poppins h-[38px] p-2 mb-3 bg-[#F3F3F3] rounded-md"
                      placeholder="Last-name"
                      required
                    />
                  </div>
  
                  <div className="container">
                    <label className="font-Poppins">Email</label>
                    <br />
                    <input
                      onChange={(e) => setshowEmail(e.target.value)}
                      type="email"
                      className="w-[371px] font-Poppins h-[38px] p-2 mb-5 bg-[#F3F3F3] rounded-md"
                      placeholder="Email"
                      required
                    />
                  </div>
  
                  <div className="container mb-3">
                    <label className="font-Poppins">Phone Number</label>
                    <br />
                    <div className="flex">
                      <select name="format" id="Num-format" className="bg-[#F3F3F3]">
                        <option value="+234">+234</option>
                        <option value="+1">+1</option>
                        <option value="+997">+997</option>
                        <option value="+01">+01</option>
                        <option value="+233">+233</option>
                        <option value="+910">+910</option>
                      </select>
                      <input
                        onChange={(e) => setshowPhoneNumber(e.target.value)}
                        id="phone"
                        type="tel"
                        name="phone"
                        pattern="({+}[0-9]{3})-[0-9]{3}-[0-9]{4}"
                        // pattern="[+]{1}[0-9]{11,14}"
                        className="w-[310px] font-Poppins h-[38px] p-2 bg-[#F3F3F3] rounded-md"
                        placeholder="+234 810910xxx"
                        required
                      />
                    </div>
                  </div>
  
                  <button
                    type="button"
                    onClick={() => setProgressTrack(1)}
                    className="bg-[#345C45] font-Poppins w-[371px] h-[48px] mt-3 text-white text-center rounded-md"
                  >
                    Next
                  </button>
                </form>
                /* End Form- Section 1 */
  
              ) : progressTrack === 1 ? (
  
                /* Confirm Email section 2 */
                <form id="ConfirmEmail" className=" mb-20">
                  <div className="container">
                    <label className="font-Poppins font">Confirm Email </label>
                    <br />
                    <input
                      onChange={(e) => setshowConfirmEmail(e.target.value)}
                      type="email"
                      id="confirmEmail"
                      name="ConfEmail"
                      className="w-[371px] font-Poppins h-[38px] p-2 mb-5 bg-[#F3F3F3] rounded-md"
                      placeholder="faruq@gmail.com"
                    />
                  </div>
  
                  <div className="flex justify-between w-[20rem] ">
                    <button
                      onClick={() => setProgressTrack(0)}
                      type="button"
                      className="bg-tranparent w-[7rem] h-[40px] border border-[#345C45] font-Poppins text-white rounded-md"
                    >
                      Back
                    </button>
                    <button
                      onClick={() => setProgressTrack(2)}
                      type="button"
                      className="bg-[#345C45] w-[7rem] font-Poppins rounded-md"
                    >
                      Next
                    </button>
                  </div>
                </form>
                /* Confirm Email End  */
  
              ) : progressTrack === 2 ? (
  
                /* Set Password section 3 */
                <form id="ConfirmEmail" className="w-[25.5rem]">
                  <div className="container">
                    <label className="font-Poppins font">Password</label>
                    <br />
                    <input
                      onChange={(e) => setshowPassword(e.target.value)}
                      type="password"
                      id="fname"
                      name="fname"
                      className="w-[371px] font-Poppins h-[38px] p-2 mb-5 bg-[#F3F3F3] rounded-md"
                      placeholder="**********"
                    />
                  </div>
  
                  <div className="container">
                    <label className="font-Poppins">Confirm Password</label>
                    <br />
                    <input
                      onChange={(e) => setshowConfirmPassword(e.target.value)}
                      type="password"
                      id="fname"
                      name="fname"
                      className="w-[371px] font-Poppins h-[38px] p-2 mb-5 bg-[#F3F3F3] rounded-md"
                      placeholder="**********"
                    />
                  </div>
  
                  <div className="flex justify-between w-[20rem] mb-7">
                    <button
                      onClick={() => setProgressTrack(1)}
                      className="bg-tranparent w-[7rem] h-[40px] border border-[#345C45] font-Poppins text-white rounded-md"
                    >
                      Back
                    </button>
                    <button
                      onClick={() => setProgressTrack(2)}
                      className="bg-[#345C45] w-[7rem] font-Poppins rounded-md"
                      type="submit"
                    >
                      Next
                    </button>
                  </div>
  
                  <div className="w-[400px] sm:w-[378px] md:w-[400px] lg:w-[400px]">
                    <div className="flex">
                      <input id="checkbox" type="checkbox" className="w-4 ml-2" />
                      <h6 className="ml-2">I agree to the Terms & Condition and Privacy Policy</h6>
                    </div>
                  </div>
                </form>
                /* Set Password End  */
              ) : null}
  
            </div>
          </div>
          {/* End RightHand side*/}
        </main>
      </div>
    );
  };
  module.exports = Signup;