import Head from "next/head";
import MainHeader from "../components/MainHeader";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Asset Tracker | Meristem Trustees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-Poppins">
        <MainHeader />
        <p>Home is where...</p>
      </main>
    </div>
  );
}
