import Head from "next/head";

const Signup = () => {
  return (
    <div>
      <Head>
        <title>Asset Tracker | Meristem Trustees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="font-Poppins text-3xl font-bold">Sign up Page</h1>
      </main>
    </div>
  );
};
export default Signup;
