import React, { useState } from "react";
import Head from "next/head";
import axios from "axios";
import { baseUrl } from "../util";
import Logocomponent from "../components/LandingPageShared/logocomponent";
//import validator from "validator";

const VerifyOtp = () => {
  const [otp, setOtp] = useState("");

  const hndleVerifyOtp = async () => {
    const response = await axios.get(`${baseUrl}/user/verify-otp/`);
  };

  return (
    <>
      <Head>
        <title>Asset Tracker | Meristem Trustees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex font-Poppins">
        <Logocomponent />

        <div className="w-full h-[100vh] flex justify-center items-center sm:pt-[10rem] bg-white mb-[8rem] ">
          <div>
            <h1 className="text-darkgreen text-[3.2rem] ">Verify Otp</h1>
            <p className="w-[38rem] sm:w-[31rem] text-black text-[1.6rem] mt-[0.1rem]">
              Enter OTP here
            </p>
            <form className=" text-black">
              <div className="flex flex-col mb-5 mt-[3rem]">
                <label className=" text-[1.4rem]">Otp</label>
                <input
                  onChange={(e) => setOtp(e.target.value)}
                  value={otp}
                  className="bg-[#F3F3F3] w-[38rem] pt-[1.6rem] pr-[1.2rem] pb-[1.4rem] pl-[1.4rem] mt-[0.4rem]  rounded-[0.5rem]"
                  id="verification-otp"
                  type="number"
                  required
                />
              </div>

              <button className="w-[38rem] bg-darkgreen font-medium text-[1.8rem] items-center text-white py-[1rem] px-[10rem] mt-[2rem] rounded-[0.5rem] ">
                Reset Password
              </button>
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default VerifyOtp;
